######################################################################
# Automatically generated by qmake (3.0) Wed Nov 9 15:20:34 2016
######################################################################

TEMPLATE = app
TARGET = qtwebsockets
INCLUDEPATH += .
QT += widgets 
QT += websockets

# Input
HEADERS += echoclient.h echoserver.h
SOURCES += echoclient.cpp echoserver.cpp main.cpp
